"""
RFC 7807 Problem Details for HTTP APIs implementation.
https://datatracker.ietf.org/doc/html/rfc7807
"""

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class ProblemDetails(BaseModel):
    """
    RFC 7807 compliant problem details model.

    This model provides a standard way to carry machine-readable details
    of errors in HTTP response bodies.
    """

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
                "title": "Bad Request",
                "status": 400,
                "detail": "The request could not be understood by the server",
                "instance": "/v1/cocktails/search",
                "errors": {
                    "freetext": ["Field is required"],
                },
            }
        }
    )

    type: str = Field(
        default="about:blank",
        description="A URI reference that identifies the problem type",
    )
    title: str = Field(description="A short, human-readable summary of the problem type")
    status: int = Field(description="The HTTP status code generated by the origin server")
    detail: str | None = Field(
        default=None,
        description="A human-readable explanation specific to this occurrence of the problem",
    )
    instance: str | None = Field(
        default=None,
        description="A URI reference that identifies the specific occurrence of the problem",
    )
    errors: dict[str, list[str]] | None = Field(
        default=None,
        description="A dictionary of validation errors, where keys are field names and values are lists of error messages",
    )
    extensions: dict[str, Any] | None = Field(
        default=None,
        description="Additional extension members for problem-specific information",
    )
