"""Filter to suppress telemetry (logs) generated by health probe requests."""

import logging
from collections.abc import Awaitable, Callable
from contextvars import ContextVar

from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import Response

_PROBE_PATHS = frozenset({"/v1/liveness", "/v1/readiness"})

_is_probe_request: ContextVar[bool] = ContextVar("is_probe_request", default=False)


class ProbeLoggingFilter(logging.Filter):
    """Drops log records that originate during a health-probe request."""

    def filter(self, record: logging.LogRecord) -> bool:
        return not _is_probe_request.get()


class ProbeTelemetryMiddleware(BaseHTTPMiddleware):
    """Sets a context flag for probe paths so the logging filter can suppress them."""

    async def dispatch(self, request: Request, call_next: Callable[[Request], Awaitable[Response]]) -> Response:
        if request.url.path in _PROBE_PATHS:
            token = _is_probe_request.set(True)
            try:
                return await call_next(request)
            finally:
                _is_probe_request.reset(token)
        return await call_next(request)
