"""Filter to suppress telemetry (logs and traces) generated by health probe requests."""

import logging
from collections.abc import Awaitable, Callable
from contextvars import ContextVar

from opentelemetry.context import _SUPPRESS_INSTRUMENTATION_KEY, attach, detach, set_value
from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import Response

PROBE_PATHS = frozenset({"/v1/liveness", "/v1/readiness"})

_is_probe_request: ContextVar[bool] = ContextVar("is_probe_request", default=False)


class ProbeLoggingFilter(logging.Filter):
    """Drops INFO/DEBUG log records that originate during a health-probe request.

    WARNING and above are always allowed through so that probe failures
    remain visible in the observability platform.
    """

    def filter(self, record: logging.LogRecord) -> bool:
        if not _is_probe_request.get():
            return True
        return record.levelno >= logging.WARNING


class ProbeTelemetryMiddleware(BaseHTTPMiddleware):
    """Suppresses logs and traces for probe paths.

    Sets a context flag so the logging filter can suppress log records,
    and sets the OpenTelemetry suppress-instrumentation flag so that
    instrumentors (e.g. HTTPX) do not create outbound spans.
    """

    async def dispatch(self, request: Request, call_next: Callable[[Request], Awaitable[Response]]) -> Response:
        if request.url.path in PROBE_PATHS:
            token = _is_probe_request.set(True)
            otel_token = attach(set_value(_SUPPRESS_INSTRUMENTATION_KEY, True))
            try:
                return await call_next(request)
            finally:
                detach(otel_token)
                _is_probe_request.reset(token)
        return await call_next(request)
