apiVersion: v1
kind: ConfigMap
metadata:
  name: cezzis-com-cocktails-aisearch-config
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
data:
  ENV: "prd"
  COCKTAILS_AISEARCH_ALLOWED_ORIGINS: "http://localhost:4001,http://localhost:4002"
  APIM_HOST_KEY: ""
  OAUTH_DOMAIN: "login.cezzis.com"
  OAUTH_AUDIENCE: "https://cezzis-aisearch-api"
  OAUTH_CLIENT_ID: "HZXyiZxjHgkQqeb6UJxmikCGYpSz5iPb"
  OAUTH_ISSUER: "https://login.cezzis.com/"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.openobserve-platform.svc.cluster.local:4318"
  OTEL_SERVICE_NAME: "cocktails-aisearch"
  OTEL_SERVICE_NAMESPACE: "cezzis"
  QDRANT_HOST: "http://qdrant.ai-platform.svc.cluster.local"
  QDRANT_PORT: "6333"
  QDRANT_API_KEY: ""
  QDRANT_COLLECTION_NAME: "cocktails-prd"
  QDRANT_VECTOR_SIZE: "768"
  QDRANT_USE_HTTPS: "false"
  QDRANT_SEMANTIC_SEARCH_LIMIT: "50"
  QDRANT_SEMANTIC_SEARCH_PREFETCH_LIMIT: "100"
  QDRANT_SEMANTIC_SEARCH_SCORE_THRESHOLD: "0.0"
  QDRANT_SEMANTIC_SEARCH_TOTAL_SCORE_THRESHOLD: "0.0"
  HUGGINGFACE_INFERENCE_MODEL: "http://tei.ai-platform.svc.cluster.local:8989"
  RERANKER_ENDPOINT: "http://tei-reranker.ai-platform.svc.cluster.local:8990"
  RERANKER_SCORE_THRESHOLD: "0.0"
  RERANKER_RELATIVE_SCORE_CUTOFF: "0.05"
  SPLADE_ENDPOINT: "http://tei-splade.ai-platform.svc.cluster.local:8991"
