apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cezzis-com-cocktails-aisearch-secrets
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cezzis-aisearch-azure-keyvault
    kind: SecretStore
  target:
    name: cezzis-com-cocktails-aisearch-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OTEL_OTLP_AUTH_HEADER: "Bearer {{ .otelApiKey }}"
        HUGGINGFACE_API_TOKEN: "{{ .embeddingsApiToken }}"
        RERANKER_API_KEY: "{{ .rerankerApiKey }}"
        SPLADE_API_KEY: "{{ .spladeApiKey }}"
  data:
    - secretKey: otelApiKey
      remoteRef:
        key: otel-collector-apikey
    - secretKey: embeddingsApiToken
      remoteRef:
        key: cocktails-aisearch-tei-embeddings-apikey
    - secretKey: rerankerApiKey
      remoteRef:
        key: cocktails-aisearch-tei-reranker-apikey
    - secretKey: spladeApiKey
      remoteRef:
        key: cocktails-aisearch-tei-splade-apikey
