apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yml
  - secret-store.yml
  - external-secret.yml
  - deployment.yml
  - service.yml
images:
  - name: acrveceusgloshared001.azurecr.io/cezziscomcocktailsaisearch
    newTag: latest
    newName: acrveceusgloshared001.azurecr.io/cezziscomcocktailsaisearch
